[package]
name = "git-rtc-odb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gix-hash = "0.14.1"
gix-odb = "0.56.1"
gix-object = "0.40.1"
tempfile = "3.9.0"
flate2 = "1.0.28"
sha1 = "0.10.6"
