[package]
name = "syn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-service = "0.3.2"
uuid = { version = "1.7.0", features = ["v4"] }
webrtc = "0.9.0"
